# Generated by Django 4.2.21 on 2025-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default='COP', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(default='Peso Colombiano', max_length=50),
        ),
    ]
