# Generated by Django 4.2.21 on 2025-05-15 04:39

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city_user_country_user_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_photo_path),
        ),
    ]
