# Generated by Django 4.2.21 on 2025-05-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_address_user_date_of_birth_user_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
