# Generated by Django 4.2.21 on 2025-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_storeschedule'),
        ('users', '0007_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_stores',
            field=models.ManyToManyField(blank=True, related_name='followers', to='stores.store'),
        ),
    ]
