# Generated by Django 4.2.21 on 2025-05-15 21:32

import apps.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=apps.stores.models.store_qr_upload_path),
        ),
    ]
