# Generated by Django 4.2.21 on 2025-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_category_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
