# Generated by Django 4.2.21 on 2025-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('pet_store', 'Mascotas'), ('motorcycle_store', 'Motos'), ('clothing', 'Ropa')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
