# Generated by Django 4.2.21 on 2025-05-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_category_icon_name_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miércoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sábado'), ('Sun', 'Domingo')], max_length=3)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stores.store')),
            ],
        ),
    ]
