# Generated by Django 4.2.21 on 2025-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_storeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('store', 'Tienda')], max_length=50),
        ),
    ]
