# Generated by Django 4.2.21 on 2025-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_remove_store_latitude_remove_store_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
