# Generated by Django 4.2.21 on 2025-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_store_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeschedule',
            name='day',
            field=models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=3),
        ),
    ]
