# Generated by Django 4.2.21 on 2025-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_storeschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeschedule',
            name='day',
            field=models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miércoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sábado'), ('Sun', 'Domingo')], max_length=3),
        ),
    ]
