# Generated by Django 4.2.21 on 2025-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_storeschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
