# Generated by Django 4.2.21 on 2025-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeschedule',
            options={'ordering': ['day']},
        ),
        migrations.AlterField(
            model_name='storeschedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
        migrations.AlterUniqueTogether(
            name='storeschedule',
            unique_together={('store', 'day')},
        ),
    ]
