# Generated by Django 4.2.21 on 2025-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_storeschedule_options_alter_storeschedule_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='storeschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='storeschedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
