# Generated by Django 4.2.21 on 2025-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_storeschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
