# Generated by Django 4.2.21 on 2025-06-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_currency_code_country_currency_name'),
        ('stores', '0019_shippingmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_days', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='stores.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.shippingzone')),
            ],
            options={
                'unique_together': {('shipping_method', 'zone')},
            },
        ),
    ]
