# Generated by Django 4.2.21 on 2025-06-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_alter_shippingmethod_cost_per_kg_shippingzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='stores.store'),
            preserve_default=False,
        ),
    ]
