# Generated by Django 4.2.21 on 2025-06-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_currency_code_country_currency_name'),
        ('stores', '0021_shippingzone_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.neighborhood'),
        ),
    ]
