# Generated by Django 4.2.21 on 2025-06-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_alter_shippingzone_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='cost_per_kg',
        ),
    ]
