# Generated by Django 4.2.21 on 2025-06-29 22:31

import apps.stores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_remove_shippingmethod_cost_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=apps.stores.models.store_qr_pay)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='stores.store')),
            ],
        ),
    ]
