# Generated by Django 4.2.21 on 2025-07-02 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRaffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prize', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='raffle_images/')),
                ('active', models.BooleanField(default=True)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
