# Generated by Django 4.2.21 on 2025-07-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_currency_code_country_currency_name'),
        ('stores', '0027_combo_comboitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingzone',
            unique_together={('store', 'country', 'city', 'neighborhood')},
        ),
    ]
