# Generated by Django 4.2.21 on 2025-07-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_alter_shippingzone_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingzone',
            unique_together=set(),
        ),
    ]
