# Generated by Django 4.2.21 on 2025-07-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_alter_shippingzone_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='name',
        ),
    ]
