# Generated by Django 4.2.21 on 2025-07-31 17:23

import apps.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_remove_shippingzone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='image',
        ),
        migrations.AddField(
            model_name='combo',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=apps.stores.models.combo_image_upload),
        ),
    ]
