# Generated by Django 4.2.21 on 2025-07-31 17:59

import apps.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_remove_combo_image_combo_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='media',
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.stores.models.combo_image_upload),
        ),
    ]
