# Generated by Django 4.2.21 on 2025-08-01 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0032_remove_combo_media_combo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='first_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
