# Generated by Django 4.2.21 on 2025-08-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_store_first_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(choices=[('standard', 'Envío estándar'), ('express', 'Entrega express'), ('same_day', 'Entrega el mismo día'), ('pickup', 'Recogida en tienda'), ('rider_delivery', 'Entrega por repartidor'), ('home_service', 'Servicio a domicilio'), ('in_store', 'Servicio en el local')], max_length=100),
        ),
    ]
