# Generated by Django 4.2.21 on 2025-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_alter_shippingmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('store', 'Tienda'), ('service', 'Servicio')], max_length=50),
        ),
    ]
