# Generated by Django 4.2.21 on 2025-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='estimated_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
