# Generated by Django 4.2.21 on 2025-08-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_alter_shippingmethod_estimated_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='estimated_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
